import Head from 'next/head';
import LayoutProfile from '../../Layout/LayoutProfile';


export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Dashboard page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutProfile>
        Dashboard page
      </LayoutProfile>

    </>
  );
}

