import Head from 'next/head';
import LayoutProfile from '../../Layout/LayoutProfile';
import { Typography, Box, Button, Container, Grid, TextField } from '@mui/material';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import { grey } from '@mui/material/colors';
import Pagination from '@mui/material/Pagination';
import FormControlLabel from '@mui/material/FormControlLabel';
import Switch from '@mui/material/Switch';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import Select from '@mui/material/Select';
import { makeStyles } from '@mui/styles';


export default function SendNews() {
  const classes = useStyls();
  return (
    <>
      <Head>
        <title>send-news page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutProfile>

        <Box display="flex" justifyContent={"space-between"}>
          <Typography variant='h6'> send news </Typography>
        </Box>
        <Box pt={3} pb={2}>
          <Grid container>
            <Grid item xs={9} pr={2}>
              <TextField fullWidth id="outlined-basic" label="News Title" variant="outlined" />
            </Grid>
            <Grid item xs={3}>
              <FormControl fullWidth>
                <InputLabel id="demo-simple-select-label">Category</InputLabel>
                <Select
                  labelId="demo-simple-select-label"
                  id="demo-simple-select"
                  value={"test"}
                  label="Category"

                >
                  <MenuItem value={10}>Ten</MenuItem>
                  <MenuItem value={20}>Twenty</MenuItem>
                  <MenuItem value={30}>Thirty</MenuItem>
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} py={2}>
              <textarea className={classes.textarea}></textarea>
            </Grid>
            <Button variant="contained">&nbsp; &nbsp; &nbsp; Send &nbsp; &nbsp; &nbsp;</Button>
          </Grid>

        </Box>
      </LayoutProfile>

    </>
  );
}


const useStyls = makeStyles({
  textarea: {
    display: 'block',
    width: '100%',
    minHeight: '300px',
    borderRadius: '10px',
    padding: '10px',
    resize: 'vertical',
  }
});

