import Head from 'next/head';
import Layout from '../Layout/Layout';
import { Box, Container, Divider, Grid, Paper, Typography, Button } from '@mui/material';
import { makeStyles } from '@mui/styles';
import HomePostItem from './../components/HomePostItem/HomePostItem';
import MenuList from '@mui/material/MenuList';
import MenuItem from '@mui/material/MenuItem';
import ListItemText from '@mui/material/ListItemText';
import ListItemIcon from '@mui/material/ListItemIcon';
import SportsBaseballIcon from '@mui/icons-material/SportsBaseball';
import AttachMoneyIcon from '@mui/icons-material/AttachMoney';
import SportsEsportsIcon from '@mui/icons-material/SportsEsports';
import LocationCityIcon from '@mui/icons-material/LocationCity';
import { teal } from '@mui/material/colors';
import Pagination from '@mui/material/Pagination';
import DateRangeIcon from '@mui/icons-material/DateRange';



export default function Archive() {

  const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  const classes = useStyls();

  return (
    <>
      <Head>
        <title>Archive page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

        <Box sx={{ bgcolor: teal[500] }} display={"flex"} justifyContent={"center"}>
          <img className={classes.imgBaner} src='images/archive01.jpg' />
        </Box>

        <Box sx={{ py: 2 }}>
          <Container maxWidth={'xl'} >

            <Grid container>
              <Grid item xs={2} sx={{ position: 'relative', paddingTop: '5px' }} >
                <Box sx={{ position: 'sticky', width: '100%', top: '8px' }}>

                  <Typography variant="h6" color="text.primary" sx={{ mb: 1 }}> category </Typography>
                  <Paper sx={{ width: 320, maxWidth: '95%' }}>
                    <MenuList>
                      <MenuItem>
                        <ListItemIcon>
                          <SportsBaseballIcon fontSize="small" />
                        </ListItemIcon>
                        <ListItemText>Sport</ListItemText>
                      </MenuItem>
                      <MenuItem>
                        <ListItemIcon>
                          <AttachMoneyIcon fontSize="small" />
                        </ListItemIcon>
                        <ListItemText>Economical</ListItemText>
                      </MenuItem>
                      <MenuItem>
                        <ListItemIcon>
                          <SportsEsportsIcon fontSize="small" />
                        </ListItemIcon>
                        <ListItemText>Game</ListItemText>
                      </MenuItem>
                      <MenuItem>
                        <ListItemIcon>
                          <LocationCityIcon fontSize="small" />
                        </ListItemIcon>
                        <ListItemText>Tourism</ListItemText>
                      </MenuItem>

                    </MenuList>
                  </Paper>



                </Box>
              </Grid>
              <Grid item xs={7} sx={{ px: 2 }}>
                <Box>
                  {
                    arr.map((item) => {
                      return (
                        <div key={item}>
                          <Paper sx={{ p: 1, mb: 2 }}>
                            <Grid container>
                              <Grid item xs="auto">
                                <img width="150" height={"140"} className={classes.imgSlide} src="images/slide1.jpg" />
                              </Grid>
                              <Grid item xs sx={{ px: 2 }}>
                                <Typography variant='h6' sx={{ mb: 2 }}>title</Typography>
                                <Typography variant='body2'>About a month after Buzzfeed News revealed the identities of its founders, Yuga Labs has started requesting customers’ personal information for an unspecified new project.</Typography>
                                <Box display={"flex"} justifyContent="right">
                                  <Box pt={2} display={"flex"} justifyContent="right" alignItems={"center"}>
                                        <DateRangeIcon />
                                        <Typography variant='caption' sx={{px: 1, paddingTop: '3px' }}>1400-02-14 | 23:45</Typography>
                                  </Box>
                                </Box>
                              </Grid>
                            </Grid>
                          </Paper>
                        </div>
                      );
                    })
                  }

                  <Pagination count={10} variant="outlined" shape="rounded" />
                </Box>
              </Grid>
              <Grid item xs={3}>
                  <img className={classes.imgADS} src='images/ADS01.webp' />
              </Grid>

            </Grid>
          </Container>
        </Box>

      </Layout>

    </>
  );
}


const useStyls = makeStyles({
  imgSlide: {
    objectFit: 'cover',
    borderRadius: '5px'
  },
  imgADS:{width: '100%'},
  imgBaner: {maxWidth: '100%'}
});
