import Head from 'next/head';
import Layout from '../components/Layout/layout';
import { Box, Container, Divider, Grid, Paper, Typography, Button } from '@mui/material';
import { makeStyles } from '@mui/styles';
import HomePostItem from './../components/HomePostItem/HomePostItem';
import MenuList from '@mui/material/MenuList';
import MenuItem from '@mui/material/MenuItem';
import ListItemText from '@mui/material/ListItemText';
import ListItemIcon from '@mui/material/ListItemIcon';
import SportsBaseballIcon from '@mui/icons-material/SportsBaseball';
import AttachMoneyIcon from '@mui/icons-material/AttachMoney';
import SportsEsportsIcon from '@mui/icons-material/SportsEsports';
import LocationCityIcon from '@mui/icons-material/LocationCity';
import { teal } from '@mui/material/colors';


export default function Archive() {

  const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  const classes = useStyls();

  return (
    <>
      <Head>
        <title>Archive page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

        <Box sx={{ bgcolor: teal[500] }} display={"flex"} justifyContent={"center"}>
            <img src='images/archive01.jpg' />
        </Box>

        <Box sx={{ py: 2 }}>
          <Container maxWidth={'xl'} >

            <Grid container>
              <Grid item xs={2} sx={{ position: 'relative', paddingTop: '5px' }} >
                <Box sx={{ position: 'sticky', width: '100%', top: '8px' }}>

                  <Typography variant="h6" color="text.primary" sx={{ mb: 1 }}> category </Typography>
                  <Paper sx={{ width: 320, maxWidth: '95%' }}>
                    <MenuList>
                      <MenuItem>
                        <ListItemIcon>
                          <SportsBaseballIcon fontSize="small" />
                        </ListItemIcon>
                        <ListItemText>Sport</ListItemText>
                      </MenuItem>
                      <MenuItem>
                        <ListItemIcon>
                          <AttachMoneyIcon fontSize="small" />
                        </ListItemIcon>
                        <ListItemText>Economical</ListItemText>
                      </MenuItem>
                      <MenuItem>
                        <ListItemIcon>
                          <SportsEsportsIcon fontSize="small" />
                        </ListItemIcon>
                        <ListItemText>Game</ListItemText>
                      </MenuItem>
                      <MenuItem>
                        <ListItemIcon>
                          <LocationCityIcon fontSize="small" />
                        </ListItemIcon>
                        <ListItemText>Tourism</ListItemText>
                      </MenuItem>

                    </MenuList>
                  </Paper>



                </Box>
              </Grid>
              <Grid item xs={10} sx={{ paddingTop: '5px' }} >
                <Box display={"flex"} justifyContent="flex-start" flexWrap={"wrap"}>
                  {
                    arr.map((item) => {
                      return (
                        <div key={item}>
                          <HomePostItem />
                        </div>
                      );
                    })
                  }
                </Box>
              </Grid>

            </Grid>

            <Box py={2} display="flex" justifyContent={"center"}>
              <Button variant="outlined">view All Posts</Button>
            </Box>
          </Container>
        </Box>

      </Layout>

    </>
  );
}


const useStyls = makeStyles({
  slideGrid: {
    // marginBottom: '-4px',
    padding: '1px',
  },
  subGrid: {
    position: 'relative',
    height: '250px',
  },
  opa: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: '#00000099',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'end',
    transition: 'all .4s ease',
    '&:hover': { backgroundColor: '#000000b3', }
  },
  imgSlide: {
    width: '100%',
    height: '250px',
    objectFit: 'cover'
  },
});
