import Head from 'next/head';
import Layout from '../components/Layout/layout';
import { Box, Container, Divider, Grid, Typography, Drawer, Avatar, Button } from '@mui/material';
import { makeStyles } from '@mui/styles';

const useStyls = makeStyles({
  slideGrid: {
    marginBottom: '-4px',
    padding: '1px',
  },
  subGrid: {
    position: 'relative',
    height: '250px',
  },
  opa: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: '#00000099',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'end',
    transition: 'all .4s ease',
    '&:hover': { backgroundColor: '#000000b3', }
  },
  imgSlide: {
    width: '100%',
    height: '250px',
    objectFit: 'cover'
  },
});

export default function Home() {

  const classes = useStyls();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

        <Box sx={{ py: 2 }}>
          <Container maxWidth={'xl'} >
            <Grid container>

              <Grid className={classes.slideGrid} item xs={6} >
                <div className={classes.subGrid}>
                  <a href='#' className={classes.opa}>
                    <Box p={1} pb={2}>
                      <Typography variant='body2' sx={{ color: 'white' }}>Biden Issues Long-Awaited Executive Order on Crypto</Typography>
                    </Box>
                  </a>
                  <img className={classes.imgSlide} src='images/slide1.jpg' />
                </div>
              </Grid>
              <Grid className={classes.slideGrid} item xs={3} >
                <div className={classes.subGrid}>
                  <a href='#' className={classes.opa}>
                    <Box p={1} pb={2}>
                      <Typography variant='body2' sx={{ color: 'white' }}>Biden Issues Long-Awaited Executive Order on Crypto</Typography>
                    </Box>
                  </a>
                  <img className={classes.imgSlide} src='images/slide1.jpg' />
                </div>
              </Grid>
              <Grid className={classes.slideGrid} item xs={3} >
                <div className={classes.subGrid}>
                  <a href='#' className={classes.opa}>
                    <Box p={1} pb={2}>
                      <Typography variant='body2' sx={{ color: 'white' }}>Biden Issues Long-Awaited Executive Order on Crypto</Typography>
                    </Box>
                  </a>
                  <img className={classes.imgSlide} src='images/slide1.jpg' />
                </div>
              </Grid>

              <Grid className={classes.slideGrid} item xs={4} >
                <div className={classes.subGrid}>
                  <a href='#' className={classes.opa}>
                    <Box p={1} pb={2}>
                      <Typography variant='body2' sx={{ color: 'white' }}>Biden Issues Long-Awaited Executive Order on Crypto</Typography>
                    </Box>
                  </a>
                  <img className={classes.imgSlide} src='images/slide1.jpg' />
                </div>
              </Grid>
              <Grid className={classes.slideGrid} item xs={4} >
                <div className={classes.subGrid}>
                  <a href='#' className={classes.opa}>
                    <Box p={1} pb={2}>
                      <Typography variant='body2' sx={{ color: 'white' }}>Biden Issues Long-Awaited Executive Order on Crypto</Typography>
                    </Box>
                  </a>
                  <img className={classes.imgSlide} src='images/slide1.jpg' />
                </div>
              </Grid>
              <Grid className={classes.slideGrid} item xs={4} >
                <div className={classes.subGrid}>
                  <a href='#' className={classes.opa}>
                    <Box p={1} pb={2}>
                      <Typography variant='body2' sx={{ color: 'white' }}>Biden Issues Long-Awaited Executive Order on Crypto</Typography>
                    </Box>
                  </a>
                  <img className={classes.imgSlide} src='images/slide1.jpg' />
                </div>
              </Grid>

            </Grid>
          </Container>
        </Box>

      </Layout>

    </>
  );
}
