import Head from 'next/head';
import { Box, Container, Divider, Grid, Typography, Drawer, Avatar, Button } from '@mui/material';
import { makeStyles } from '@mui/styles';
import TextField from '@mui/material/TextField';
import { blue } from '@mui/material/colors';






export default function Login() {

  const classes = useStyls();

  return (
    <>
      <Head>
        <title>login page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Grid container sx={{ minHeight: '100vh' }}>
        <Grid item xs={6}><img src="images/login-background.jpg" className={classes.imgBack} /></Grid>
        <Grid item xs={6} display="flex" justifyContent={"center"} flexDirection="column" alignItems={"center"}>
          <Box px={2} display="flex" justifyContent={"center"} flexDirection="column" alignItems={"center"} sx={{ width: '430px' , maxWidth: '100%' }}>
            <img style={{ marginBottom: 50 }} width={80} src='images/logo.png' />
            <TextField sx={{ my: 1 }}
              fullWidth
              size="small"
              id="outlined-basic"
              label="Email"
              variant="outlined"
            />

            <TextField sx={{ my: 1 }}
              fullWidth
              size="small"
              type={"password"}
              id="outlined-basic"
              label="Password"
              variant="outlined"
            />

            <Box sx={{ width: '100%' }} pt={3} pb={1}>
              <Button fullWidth my={5} variant="contained">Login</Button>
            </Box>
            <Box sx={{ width: '100%' }} pt={1} pb={12} display="flex" justifyContent={"space-between"}>
              <Typography fontSize={"small"} sx={{color: blue[500] , cursor: 'pointer' }}>Forgot password?</Typography>
              <Typography fontSize={"small"} sx={{color: blue[500] , cursor: 'pointer' }}>Don't have an account? Sign Up</Typography>
            </Box>

            <Typography fontSize={"small"}>Copyright © hojjat and mehdi :) 2022.</Typography>

          </Box>
        </Grid>
      </Grid>

    </>
  );
}


const useStyls = makeStyles({
  imgBack: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover'

  }
});